### ISSUE TITLE
Mode sandbox

### ISSUE THREAD

**Issue by Djibs** [k-angama/iOS-LinkyAPI#2]
Salut,

Merci pour ton travail.

Une fois que je suis connecté à Enedis et que j'ai donné mon autorisation, la webview se ferme et j'ai une erreur :

![Capture ecran 2024-01-05 à 19 05 18](https://github.com/k-angama/iOS-LinkyAPI/assets/1236842/de317a88-69ce-43d4-940b-46384f677d1f)

Pour faire mon teste, j'utilise le mode .sandbox(prm: .client2(.prm1))
Et pour REDIRECT_URI j'ai crée une url_type : monApp://

il y a peu être de paramétrages que j'ai loupé dans le plist?

Merci

**Comment by k-angama** [comment]
Salut,

Merci pour ton retour.
Le mode sandbox est utilisé pour pouvoir tester l'API en mode développement.
En mode sandbox, il y a plusieurs types d'utilisateurs que tu peux définir ainsi que leur PRM (leur numéro Linky). Chaque client peut avoir un ou plusieurs PRM, ce qui permet de tester différents cas de figure.

Tu peux trouver le cas de chaque client ici : https://github.com/k-angama/iOS-LinkyAPI/blob/main/Sources/LinkyAPI/Configuration/LinkySandboxPRM.swift

Concernant l'erreur, as-tu pu faire une demande d'accès côté Enedis, comme indiqué dans le README ? Il te  faut créer un compte développeur.

`Avant d'intégrer la bibliothèque API Linky dans votre application Swift, plusieurs étapes préalables doivent être réalisées, vous devez créer un compte développeur chez Enedis. Au cours de ce processus, vous obtiendrez des informations d'identification essentielles, notamment un CLIENT_ID et un CLIENT_SECRET. De plus, vous devez enregistrer une application spécifique à votre utilisation de l'API Linky. Cette inscription nécessite généralement de fournir un numéro SIRET valide et de conclure un accord contractuel avec Enedis.`

J'ai effectué quelques tests, ça a l'air de bien fonctionner de mon côté. ^^

**Comment by Djibs** [comment]
J'ai bien signé le contrat avec Enedis, et j'ai généré mon app. Mais je me dis que j'ai peu etre fais une erreur sur le client_ID. C'est bien la clé publique ?

EN me connectant avec mon compte à Enedis, ca me monte le PDL /PRM de mon linky perso et me demande  de valider après avoir accepté.
.
![Capture ecran 2024-01-05 à 23 21 26](https://github.com/k-angama/iOS-LinkyAPI/assets/1236842/c66a0fb1-9882-455c-bd20-ba69382ba2d5)

![Capture ecran 2024-01-06 à 00 26 39](https://github.com/k-angama/iOS-LinkyAPI/assets/1236842/5c8880e9-7fb5-444d-972e-c269e3a9e6b4)

**Comment by k-angama** [comment]
Oui, le client_ID correspond bien à la clé publique. Il faut également accepter toutes les conditions. Ta souscription doit être validée par Enedis.

![Capture d’écran 2024-01-06 à 11 14 22](https://github.com/k-angama/iOS-LinkyAPI/assets/11558339/c1b134f9-6abd-46db-a18d-54ef8f60b590)

**Comment by Djibs** [comment]
je confirme ma souscription est bien validée.

![Capture ecran 2024-01-06 à 12 15 19](https://github.com/k-angama/iOS-LinkyAPI/assets/1236842/2d499a59-d2e6-4c0d-a089-d1c0a5b9bd5d)

**Comment by k-angama** [comment]
Peux-tu me montrer le code que tu as mis en place ?

**Comment by Djibs** [comment]
le voici, mais il n'y a rien de particulier : 

`
    struct AuthorizationView: View {

    @EnvironmentObject var sunViewModel: SunViewModel

    @Environment(\.presentationMode) var presentationMode

    @State private var linkyAuth: LinkyAuthorization
    @State private var showAlert = false
    @State private var alertMessage = ""
    @State private var showContentChart = false
    @State private var showDisclosureGroup = true
    @State private var termsAccepted = false

    init() {
        let configuration = LinkyConfiguration(
            clientId: Resources.DataConnectEnedis.clientID,
            clientSecret: Resources.DataConnectEnedis.clientSecret,
            redirectURI: URL(string: Resources.DataConnectEnedis.callbackURLScheme)!,
            mode: .sandbox(prm: .client7(.prm2)),
            duration: .year(value: 3)
        )
        _linkyAuth = State(initialValue: LinkyAuthorization(configuration: configuration))
    }


    var body: some View {

        ZStack{
            BackgroundView()

            ScrollView {

                        VStack(alignment: .leading, spacing: 20) {

                            Button(action: {
                                    self.presentationMode.wrappedValue.dismiss()
                            }, label:  {
                                HStack {
                                    Image(systemName: "chevron.backward")
                                        .foregroundStyle(.white.opacity(0.5))
                                        .font(.title2)
                                    Spacer()
                                }
                            })
                            .accessibilityLabel("Retour")

                            Text("En association avec Enedis, accédez au suivi de votre consommation électrique à J+1")
                                .font(.headline)
                                .padding(.bottom)

                            Text("Pourquoi faire ?")
                                .font(.title2)

                            VStack(alignment: .leading, spacing: 8) {
                                HStack {
                                    Image(systemName: "checkmark.circle.fill")
                                        .foregroundColor(.green)
                                    Text("Reprendre le contrôle de votre consommation")
                                }

                                HStack {
                                    Image(systemName: "checkmark.circle.fill")
                                        .foregroundColor(.green)
                                    Text("Détecter une défaillance, anticiper la maintenance")
                                }

                                HStack {
                                    Image(systemName: "checkmark.circle.fill")
                                        .foregroundColor(.green)
                                    Text("Identifier les appareils énergivores")
                                }
                            }
                            .padding(.leading)
                            .font(.callout)

                            HStack {
                                Image(systemName: "checkmark.shield")
                                    .foregroundColor(.cyan)

                                Text("Vos données de consommation ne sortent pas de votre appareil, elles ne sont ni vendues, ni partagées.")
                                    .font(.footnote)
                            }
                            .modifier(SectionModifier(title: ""))
                            .padding(.top, -10)

                            DisclosureGroup(isExpanded: $showDisclosureGroup) {
                                VStack(alignment: .leading, spacing: 8) {
                                    Text("• La courbe de charge").bold() + Text(" : la consommation électrique de votre logement de la veille toutes les 30 ou 60 minutes")
                                    Text("• Les index quotidiens").bold() + Text(" : les index envoyés au gestionnaire de réseau Enedis en fonction des besoins")
                                    Text("• Puissance maximale quotidienne").bold() + Text(" : puissance maximale atteinte durant la journée")
                                }
                                .padding(.top)
                                .padding(.leading)
                                .font(.callout)

                            } label: {
                                Text("Quelles sont les données utilisées ?")
                                    .font(.title3)
                            }
                        }
                        .modifier(SectionModifier(title: ""))

                VStack(alignment: .leading){
                    HStack {
                        Toggle("", isOn: $termsAccepted)
                            .toggleStyle(CheckboxToggleStyle())
                            .onTapGesture {
                                termsAccepted.toggle()
                            }

                        Text("Je déclare sur l'honneur être le titulaire du point ou être mandaté par celui-ci et j'accepte que tempo Bleu Blanc Rouge ait accès à mes données des 2 ans passés et pour les 3 ans à venir. Je peux changer d'avis à tout moment sur mon compte Enedis.")
                            .font(.caption)
                            .frame(width: 280, height: 70, alignment: .leading)
                    }
                }
                .modifier(SectionModifier(title: ""))

                // Bouton S'inscrire

                Button(action: {
                    openAuthorization()
                }) {
                    HStack {
                        Spacer()
                        Text("S'authentifier sur Enedis")
                        Spacer()
                    }

                }
                .modifier(SectionModifier(title: ""))
                .opacity(termsAccepted ? 1 : 0.5)
                .disabled(!termsAccepted)
                .padding(.bottom)

            }
            .padding()
            //.ignoresSafeArea()
        }
        .edgesIgnoringSafeArea([.horizontal, .bottom])
        .alert(isPresented: $showAlert) {
            Alert(title: Text("Message"), message: Text(alertMessage), dismissButton: .default(Text("OK")))
        }

    }

    private func openAuthorization() {
        linkyAuth.authorization { error in
            if let error = error {
                self.alertMessage = "Erreur API\n\(error.localizedDescription)"
                self.showAlert = true
            } else {
                // ...
            }
        }
    }
}
`

**Comment by k-angama** [comment]
J'ai testé ton code avec mes accès Enedis, et ça a l'air de bien fonctionner. Je sais que j'ai dû attendre quelques semaines avant que mon compte soit vraiment actif. Sinon, essaie de les contacter directement pour avoir plus d'infos.

**Comment by Djibs** [comment]
Merci.
je viens de voir que dejà sur mon compte  la "Collecte de la consommation horaire " par Enedis était désactivée. Je viens de l'activer mais il est indiqué que je dois attendre quelques heures.
je te dirai si le probleme vient de là.

**Comment by Djibs** [comment]
Même en activant la Collecte de la consommation horaire sur mon compte le soucis est toujours présent. Je vais donc attendre un peu.

**Comment by Djibs** [comment]
je viens de voir que l'authentification n'est disponible que lorsque l'application est en production : 

https://datahub-enedis.fr/services-api/data-connect/documentation/autorisation-v1/

Mon app est toujours dans le bac à sable. tu as mis ton app  en prod ?

![Capture ecran 2024-01-07 à 15 33 14](https://github.com/k-angama/iOS-LinkyAPI/assets/1236842/c5abd75f-a766-41a1-b6cf-3a22c540a7f6)

**Comment by k-angama** [comment]
Non, pas besoin que l'app soit en prod côté Enedis pour pouvoir tester en mode sandbox. La mienne n'est toujours pas en prod, le mode sandbox sert à ça justement. Tu as toujours le même problème ?

**Comment by Djibs** [comment]
Oui toujours.
Du coup j'ai envoyé un message à Enedis, ca me parait bizarre de devoir attendre plusieurs semaines.

**Comment by k-angama** [comment]
Je sais pas si tu as eu une réponse d'Enedis, mais le mieux c'est de les contacter par ici : https://datahub-enedis.fr/services-api/contacter-le-service-api/

**Comment by Djibs** [comment]
non pas encore eu de réponse.
je les ai contacté depuis la même page.

**Comment by k-angama** [comment]
Le mieux ça serait que je puisse tester avec tes accès, je pourrais peut-être voir d'où vient le problème. Si tu es d'accord du peux m'envoyer des messages perso à partir de mon site : https://www.kangama.com/contact/

**Comment by Djibs** [comment]
je t'ai fais un demande sur linkedin ce sera plus facile.

**Comment by k-angama** [comment]
Le problème provenait du format incorrect de l'URI de redirection. S'il n'était pas correctement formaté, cela empêchait le mode sandbox de fonctionner correctement. Le problème a été résolu dans la version 1.0.1 : #3

**Comment by Djibs** [comment]
Merci
